# Generated by Django 4.0.6 on 2022-07-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLogModel',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('search_parameters', models.CharField(max_length=200)),
                ('year_more_results', models.CharField(max_length=50)),
                ('year_less_results', models.CharField(max_length=50)),
                ('actor_more_appearances', models.CharField(max_length=50)),
                ('actor_less_appearances', models.CharField(max_length=50)),
                ('rating_min', models.FloatField()),
                ('rating_max', models.FloatField()),
                ('rating_mean', models.FloatField()),
                ('rating_median', models.FloatField()),
                ('rating_std', models.FloatField()),
            ],
        ),
    ]
